# Generated by Django 4.2.13 on 2026-06-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=50)),
                ('health_score', models.FloatField(default=0)),
                ('roe', models.FloatField(default=0)),
                ('opm', models.FloatField(default=0)),
                ('debt_to_equity', models.FloatField(default=0)),
                ('revenue_growth', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sales', models.BigIntegerField(default=0)),
                ('net_profit', models.BigIntegerField(default=0)),
                ('opm_pct', models.FloatField(default=0)),
                ('eps', models.FloatField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'unique_together': {('company', 'year')},
            },
        ),
    ]
