# Generated by Django 4.2.13 on 2026-06-02 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdata',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='financialdata',
            name='borrowings',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='debt_to_equity_calc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='reserves',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='total_assets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='debt_to_equity',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='company',
            name='health_score',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='company',
            name='opm',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue_growth',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='roe',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='api.company'),
        ),
    ]
